x-logging-defaults: &logging-defaults
  driver: json-file
  options:
    max-size: 500k
    max-file: 10

services:
  postgres:
    container_name: dash.postgres
    image: "postgres:16-alpine"
    hostname: dash.postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - dash.postgres.network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - dash.postgres.data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      <<: *logging-defaults


volumes:
  dash.postgres.data: {}

networks:
  dash.postgres.network: {}