carwash_config = {
    "OTA_port": 80,
    "timeZone": 2,
    "OTA_server": "http://",
    "bill_table": [
        1,
        2,
        5,
        10,
        20,
        50,
        100,
        200,
        500,
        1000,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    "broker_uri": "mqtt://test_broker_1.com",
    "coin_table": [50, 100, 100, 200, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "ntp_server": "test_ntp_1.com",
    "broker_pass": "qwertyu",
    "broker_port": 1883,
    "broker_user": "E4001784DBE8",
    "last_update": "1970-01-01T00:00:00",
    "wifi_STA_ssid": "test_1",
    "wifi_STA_pass": "12345678",
    "coinPulsePrice": 50,
    "coinValidatorType": "protocol",
}
wsm_config = {
    "OTA_port": 80,
    "timeZone": 2,
    "OTA_server": "http://",
    "bill_table": [
        1,
        2,
        5,
        10,
        20,
        50,
        100,
        200,
        500,
        1000,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    "broker_uri": "mqtt://test_broker_2.com",
    "coin_table": [50, 100, 100, 200, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "ntp_server": "test_ntp_2.com",
    "broker_pass": "qwertyu",
    "broker_port": 1883,
    "broker_user": "E4001784DBE8",
    "last_update": "1970-01-01T00:00:00",
    "wifi_STA_pass": "12345678",
    "wifi_STA_ssid": "test_2",
    "coinPulsePrice": 50,
    "coinValidatorType": "protocol",
}

carwash_settings = {
    "maxPayment": None,
    "minPayPass": 100,
    "maxPayPass": 20000,
    "deltaPayPass": 100,
    "timeOnePay": 600,
    "timePause": 60,
    "servicesRelay": {
        "foam": [1, 2, 6, 10],
        "foam_extra": [1, 2, 6, 9, 10],
        "water_pressured": [2, 11],
        "water_warm": [3, 11],
        "osmos": [11],
        "wax": [2, 7, 11],
        "winter": [3, 8, 11],
        "blackening": [5],
    },
    "servicesPause": {
        "foam": 5,
        "foam_extra": 5,
        "water_pressured": 5,
        "water_warm": 5,
        "osmos": 5,
        "wax": 5,
        "winter": 5,
        "blackening": 5,
    },
    "vfdFrequency": {
        "foam": 45,
        "foam_extra": 47,
        "water_pressured": 50,
        "water_warm": 40,
        "osmos": 30,
        "wax": 35,
        "winter": 41,
        "blackening": 0,
    },
    "tariff": {
        "foam": 1000,
        "foam_extra": 2000,
        "water_pressured": 100,
        "water_warm": 150,
        "osmos": 200,
        "wax": 500,
        "winter": 600,
        "blackening": 800,
    },
    "pulsesPerLiter": 450,
    "enableSrcAfterPause": None,
    "timeLight": 5000,
    "timeTechnicalMode": 300,
}
wsm_settings = {
    "maxPayPass": 20000,
    "maxPayment": 20000,
    "minPayPass": 100,
    "spillTimer": 0,
    "timeOnePay": 300,
    "last_update": "1970-01-01T00:00:00",
    "spillAmount": 0,
    "deltaPayPass": 100,
    "timeServisMode": 600,
    "litersInFullTank": 7500,
    "pulsesPerLiter_1": 450,
    "pulsesPerLiter_2": 451,
    "pulsesPerLiter_3": 451,
    "tariffPerLiter_1": 150,
    "tariffPerLiter_2": 200,
}

wsm_state = {
    "created": "2025-05-28T18:30:52+02:00",
    "summaInBox": 0,
    "litersInTank": 7500,
    "operatingMode": "WAIT",
    "tankLowLevelSensor": True,
    "tankHighLevelSensor": True,
    "depositBoxSensor": False,
    "doorSensor": False,
    "coinState": 0,
    "billState": 0,
    "errors": {
        "lowLevelSensor": False,
        "ServerBlock": False,
        "pour_1": False,
        "pour_2": False,
        "coinValidator": False,
        "billValidator": True,
        "PayPass": False,
        "Card": False,
    },
}

carwash_state = {
    "created": "2025-08-05T02:13:30+02:00",
    "summaInBox": 0,
    "operatingMode": "WAIT",
    "service": "pause",
    "timer": "04:49",
    "summa": 763.25,
    "depositBoxSensor": False,
    "doorSensor": False,
    "coinState": 0,
    "billState": 0,
    "sensors": {"hum": 29, "temp": [39, -99, -99]},
    "ext_sensors": {"hum": 44, "temp": [31, -99, -99]},
    "errors": {
        "ServerBlock": False,
        "ExtPlata": False,
        "PresenceWater": False,
        "reserv": False,
        "coinValidator": False,
        "billValidator": True,
        "PayPass": False,
        "Card": False,
    },
}

fiscalizer_state = {
    "created": "2025-08-05T03:10:33+03:00",
    "input": False,
    "bill_state": 20,
}

laundry_state = {
    "relay": [{"id": 0, "state": False}, {"id": 1, "state": False}],
    "output": [
        {"id": 0, "state": False},
        {"id": 1, "state": False},
        {"id": 2, "state": False},
        {"id": 3, "state": False},
        {"id": 4, "state": False},
        {"id": 5, "state": False},
    ],
    "input": [{"id": 0, "state": False}, {"id": 1, "state": True}],
}

mock_energy_state = {
    "created": "2025-05-28T20:36:18",
    "energy_total_since": "2025-04-04T14:59:51",
    "energy_total": 7.653,
    "energy_yesterday": 0.380,
    "energy_today": 0.492,
    "power": 0,
    "apparent_power": 0,
    "reactive_power": 0,
    "power_factor": 0.00,
    "voltage": 221,
    "current": 0.000,
}

fiscalizer_config = {
    "last_update": "2025-06-23T11:19:52+02:00",
    "wifi_STA_ssid": "test_3",
    "wifi_STA_pass": "12345678",
    "ntp_server": "test_ntp_3.com",
    "timeZone": 2,
    "broker_uri": "mqtt://test_broker_3.com",
    "broker_port": 1883,
    "broker_user": "BC4E1784DBE8",
    "broker_pass": "qwertyu",
    "OTA_server": "http://",
    "OTA_port": 80,
}

fiscalizer_settings = {
    "last_update": "1970-01-01T00:00:00+02:00",
    "interface": {"controller": "ccnet", "validator": "ccnet", "coin": "pulsed"},
    "simulatorMC_pulse_price": 1,
    "bill_pulse_price": 1,
    "coin_pulse_price": 1,
    "simulatorMC_table": [
        1,
        2,
        5,
        10,
        20,
        50,
        100,
        200,
        500,
        1000,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    "bill_table": [
        1,
        2,
        5,
        10,
        20,
        50,
        100,
        200,
        500,
        1000,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    "coin_table": [50, 100, 100, 200, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "fiscalizationTime": 30,
}

laundry_config = {
    "request_id": 135,
    "last_update": "",
    "pppos_apn": "internet",
    "wifi_STA_ssid": "4G-CPE_9888",
    "wifi_STA_pass": "1234567890",
    "ntp_server": "pool.ntp.org",
    "timeZone": 3,
    "broker_uri": "mqtt://mqtt.npc.com.ua",
    "broker_port": 1883,
    "broker_user": "2001315C7BCC",
    "broker_pass": "qwertyu",
    "OTA_server": "http://",
    "OTA_port": 80,
    "laundry_status": "AVAILABLE",
}

laundry_settings = {
    "request_id": 135,
    "last_update": "",
    "inputCBT": [{"id": 0, "value": 100}, {"id": 1, "value": 100}],
    "input_to_relay": [
        {"input": 0, "relay": 0, "value": False},
        {"input": 0, "relay": 1, "value": False},
        {"input": 1, "relay": 0, "value": False},
        {"input": 1, "relay": 1, "value": False},
    ],
}

car_cleaner_config = {
    "OTA_port": 80,
    "timeZone": 2,
    "OTA_server": "http://",
    "bill_table": [
        1,
        2,
        5,
        10,
        20,
        50,
        100,
        200,
        500,
        1000,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    "broker_uri": "mqtt://test_broker_4.com",
    "coin_table": [50, 100, 100, 200, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "ntp_server": "test_ntp_4.com",
    "broker_pass": "qwertyu",
    "broker_port": 1883,
    "broker_user": "CC4E1784DBE8",
    "last_update": "1970-01-01T00:00:00",
    "wifi_STA_ssid": "test_4",
    "wifi_STA_pass": "12345678",
    "coinPulsePrice": 50,
    "coinValidatorType": "protocol",
}

car_cleaner_settings = {
    "maxPayment": None,
    "minPayPass": 100,
    "maxPayPass": 20000,
    "deltaPayPass": 100,
    "timeOnePay": 600,
    "timePause": 60,
    "servicesRelay": {
        "vacuum_cleaner": [1, 2, 6, 10],
        "wet_vacuum_cleaner": [1, 2, 6, 9, 10],
        "steam_vacuum_cleaner": [2, 11],
        "blowing": [3, 11],
        "sprayer": [11],
        "tornadore": [2, 7, 11],
    },
    "servicesPause": {
        "vacuum_cleaner": 5,
        "wet_vacuum_cleaner": 5,
        "steam_vacuum_cleaner": 5,
        "blowing": 5,
        "sprayer": 5,
        "tornadore": 5,
    },
    "tariff": {
        "vacuum_cleaner": 1000,
        "wet_vacuum_cleaner": 2000,
        "steam_vacuum_cleaner": 100,
        "blowing": 150,
        "sprayer": 200,
        "tornadore": 500,
    },
    "pulsesPerLiter": 450,
    "enableSrcAfterPause": None,
    "timeLight": 5000,
    "timeTechnicalMode": 300,
}

car_cleaner_state = {
    "created": "2025-08-05T02:13:30+02:00",
    "summaInBox": 0,
    "operatingMode": "WAIT",
    "service": "pause",
    "timer": "04:49",
    "summa": 763.25,
    "depositBoxSensor": False,
    "doorSensor": False,
    "coinState": 0,
    "billState": 0,
    "sensors": {"hum": 29, "temp": [39, -99, -99]},
    "ext_sensors": {"hum": 44, "temp": [31, -99, -99]},
    "errors": {
        "ServerBlock": False,
        "ExtPlata": False,
        "PresenceWater": False,
        "reserv": False,
        "coinValidator": False,
        "billValidator": True,
        "PayPass": False,
        "Card": False,
    },
}
vacuum_config = {
    "OTA_port": 80,
    "timeZone": 2,
    "OTA_server": "http://",
    "bill_table": [
        1,
        2,
        5,
        10,
        20,
        50,
        100,
        200,
        500,
        1000,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    "broker_uri": "mqtt://test_broker_4.com",
    "coin_table": [50, 100, 100, 200, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    "ntp_server": "test_ntp_4.com",
    "broker_pass": "qwertyu",
    "broker_port": 1883,
    "broker_user": "CC4E1784DBE8",
    "last_update": "1970-01-01T00:00:00",
    "wifi_STA_ssid": "test_4",
    "wifi_STA_pass": "12345678",
    "coinPulsePrice": 50,
    "coinValidatorType": "protocol",
}

vacuum_settings = {
    "maxPayment": None,
    "minPayPass": 100,
    "maxPayPass": 20000,
    "deltaPayPass": 100,
    "timeOnePay": 600,
    "timePause": 60,
    "servicesRelay": {
        "vacuum_cleaner": [1, 2, 6, 10],
        "blowing": [1, 2, 6, 9, 10],
        "wheel_inflation": [2, 11],
        "glass_washer": [3, 11],
        "blackening": [11],
    },
    "servicesPause": {
        "vacuum_cleaner": 5,
        "blowing": 5,
        "wheel_inflation": 5,
        "glass_washer": 5,
        "blackening": 5,
    },
    "tariff": {
        "vacuum_cleaner": 1000,
        "blowing": 2000,
        "wheel_inflation": 100,
        "glass_washer": 150,
        "blackening": 200,
    },
    "pulsesPerLiter": 450,
    "enableSrcAfterPause": None,
    "timeLight": 5000,
    "timeTechnicalMode": 300,
}

vacuum_state = {
    "created": "2025-08-05T02:13:30+02:00",
    "summaInBox": 0,
    "operatingMode": "WAIT",
    "service": "pause",
    "timer": "04:49",
    "summa": 763.25,
    "depositBoxSensor": False,
    "doorSensor": False,
    "coinState": 0,
    "billState": 0,
    "sensors": {"hum": 29, "temp": [39, -99, -99]},
    "ext_sensors": {"hum": 44, "temp": [31, -99, -99]},
    "errors": {
        "ServerBlock": False,
        "ExtPlata": False,
        "PresenceWater": False,
        "reserv": False,
        "coinValidator": False,
        "billValidator": True,
        "PayPass": False,
        "Card": False,
    },
}
