"""update customers

Revision ID: 003
Revises: 002
Create Date: 2025-05-14 01:53:27.776795

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customers",
        sa.Column(
            "tariff_per_liter_1", sa.Numeric(precision=10, scale=2), nullable=True
        ),
    )
    op.add_column(
        "customers",
        sa.Column(
            "tariff_per_liter_2", sa.Numeric(precision=10, scale=2), nullable=True
        ),
    )
    op.add_column("customers", sa.Column("birth_date", sa.Date(), nullable=True))
    op.add_column("customers", sa.Column("phone_number", sa.String(), nullable=True))
    op.add_column(
        "customers", sa.Column("discount_percent", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "discount_percent")
    op.drop_column("customers", "phone_number")
    op.drop_column("customers", "birth_date")
    op.drop_column("customers", "tariff_per_liter_2")
    op.drop_column("customers", "tariff_per_liter_1")
    # ### end Alembic commands ###
