"""update controllers and payments

Revision ID: 003
Revises: 002
Create Date: 2025-04-21 20:04:57.579059

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "controllers", sa.Column("monopay_active", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE controllers SET monopay_active = FALSE")
    op.alter_column("controllers", "monopay_active", nullable=False)
    op.add_column(
        "controllers", sa.Column("liqpay_public_key", sa.String(), nullable=True)
    )
    op.add_column(
        "controllers", sa.Column("liqpay_private_key", sa.String(), nullable=True)
    )
    op.add_column(
        "controllers", sa.Column("liqpay_active", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE controllers SET liqpay_active = FALSE")
    op.alter_column("controllers", "liqpay_active", nullable=False)
    sa.Enum("CARWASH", "VENDING", name="locationtype").drop(op.get_bind())
    op.sync_enum_values(
        enum_schema="public",
        enum_name="paymenttype",
        new_values=["BILL", "COIN", "PAYPASS", "MONOPAY", "LIQPAY", "FREE"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="payments", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="paymenttype",
        new_values=["BILL", "COIN", "PAYPASS", "MONOPAY", "FREE"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="payments", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    sa.Enum("CARWASH", "VENDING", name="locationtype").create(op.get_bind())
    op.drop_column("controllers", "liqpay_active")
    op.drop_column("controllers", "liqpay_private_key")
    op.drop_column("controllers", "liqpay_public_key")
    op.drop_column("controllers", "monopay_active")
    # ### end Alembic commands ###
