"""add transactions.customer_id

Revision ID: 004
Revises: 003
Create Date: 2025-05-14 01:55:00.413619

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "004"
down_revision: Union[str, None] = "003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("customer_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "transactions_customer_id_fk",
        "transactions",
        "customers",
        ["customer_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "transactions_customer_id_fk", "transactions", type_="foreignkey"
    )
    op.drop_column("transactions", "customer_id")
    # ### end Alembic commands ###
