"""add encashments

Revision ID: 006
Revises: 005
Create Date: 2025-05-15 22:56:57.730941

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "006"
down_revision: Union[str, None] = "005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "encashments",
        sa.Column("controller_id", sa.UUID(), nullable=False),
        sa.Column("coin_1", sa.Integer(), nullable=False),
        sa.Column("coin_2", sa.Integer(), nullable=False),
        sa.Column("coin_3", sa.Integer(), nullable=False),
        sa.Column("coin_4", sa.Integer(), nullable=False),
        sa.Column("coin_5", sa.Integer(), nullable=False),
        sa.Column("coin_6", sa.Integer(), nullable=False),
        sa.Column("bill_1", sa.Integer(), nullable=False),
        sa.Column("bill_2", sa.Integer(), nullable=False),
        sa.Column("bill_3", sa.Integer(), nullable=False),
        sa.Column("bill_4", sa.Integer(), nullable=False),
        sa.Column("bill_5", sa.Integer(), nullable=False),
        sa.Column("bill_6", sa.Integer(), nullable=False),
        sa.Column("bill_7", sa.Integer(), nullable=False),
        sa.Column("bill_8", sa.Integer(), nullable=False),
        sa.Column("encashed_amount", sa.Integer(), nullable=False),
        sa.Column("received_amount", sa.Integer(), nullable=True),
        sa.Column("created_at_controller", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["controller_id"],
            ["controllers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("encashments")
    # ### end Alembic commands ###
