"""add company privacy_policy and offer_agreement

Revision ID: 007
Revises: 006
Create Date: 2025-05-20 18:19:43.742155

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "007"
down_revision: Union[str, None] = "006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("privacy_policy", sa.String(), nullable=True))
    op.add_column("companies", sa.Column("offer_agreement", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "offer_agreement")
    op.drop_column("companies", "privacy_policy")
    # ### end Alembic commands ###
