"""update transactions

Revision ID: 008
Revises: 007
Create Date: 2025-05-22 09:44:26.248419

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "008"
down_revision: Union[str, None] = "007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "carwash_transactions",
        sa.Column(
            "services_sold_seconds",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
    )
    op.add_column(
        "carwash_transactions",
        sa.Column("tariff", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column(
        "carwash_transactions",
        sa.Column("replenishment_ratio", sa.Integer(), nullable=True),
    )

    op.add_column("transactions", sa.Column("sale_type", sa.String(), nullable=True))
    op.execute(
        """
        UPDATE transactions t
        SET sale_type = wt.sale_type
        FROM water_vending_transactions wt
        WHERE wt.transaction_id = t.id
        """
    )
    op.alter_column("transactions", "sale_type", nullable=False)

    op.add_column(
        "transactions", sa.Column("card_balance_in", sa.Integer(), nullable=True)
    )
    op.add_column(
        "transactions", sa.Column("card_balance_out", sa.Integer(), nullable=True)
    )
    op.add_column("transactions", sa.Column("card_uid", sa.String(), nullable=True))
    op.drop_column("water_vending_transactions", "sale_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "water_vending_transactions",
        sa.Column("sale_type", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.execute(
        """
        UPDATE water_vending_transactions wt
        SET sale_type = t.sale_type
        FROM transactions t
        WHERE wt.transaction_id = t.id
        """
    )
    op.alter_column("water_vending_transactions", "sale_type", nullable=False)

    op.drop_column("transactions", "card_uid")
    op.drop_column("transactions", "card_balance_out")
    op.drop_column("transactions", "card_balance_in")
    op.drop_column("transactions", "sale_type")
    op.drop_column("carwash_transactions", "replenishment_ratio")
    op.drop_column("carwash_transactions", "tariff")
    op.drop_column("carwash_transactions", "services_sold_seconds")
    # ### end Alembic commands ###
