"""add checkbox fields

Revision ID: 009
Revises: 008
Create Date: 2025-05-26 11:31:07.085559

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "009"
down_revision: Union[str, None] = "008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "controllers", sa.Column("checkbox_login", sa.String(), nullable=True)
    )
    op.add_column(
        "controllers", sa.Column("checkbox_password", sa.String(), nullable=True)
    )
    op.add_column(
        "controllers", sa.Column("checkbox_license_key", sa.String(), nullable=True)
    )

    op.add_column(
        "controllers", sa.Column("checkbox_active", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE controllers SET checkbox_active = false;")
    op.alter_column("controllers", "checkbox_active", nullable=False)

    op.add_column("controllers", sa.Column("good_name", sa.String(), nullable=True))
    op.add_column("controllers", sa.Column("good_code", sa.String(), nullable=True))
    op.add_column("controllers", sa.Column("tax_code", sa.String(), nullable=True))
    op.add_column("payments", sa.Column("receipt_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "receipt_id")
    op.drop_column("controllers", "tax_code")
    op.drop_column("controllers", "good_code")
    op.drop_column("controllers", "good_name")
    op.drop_column("controllers", "checkbox_active")
    op.drop_column("controllers", "checkbox_license_key")
    op.drop_column("controllers", "checkbox_password")
    op.drop_column("controllers", "checkbox_login")
    # ### end Alembic commands ###
