"""add daily_energy_states

Revision ID: 011
Revises: 010
Create Date: 2025-05-27 18:27:34.709750

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "011"
down_revision: Union[str, None] = "010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_energy_states",
        sa.Column("controller_id", sa.UUID(), nullable=False),
        sa.Column("energy", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["controller_id"],
            ["controllers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("controllers", sa.Column("tasmota_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("controllers", "tasmota_id")
    op.drop_table("daily_energy_states")
    # ### end Alembic commands ###
