"""add transactions.card_amount

Revision ID: 013
Revises: 012
Create Date: 2025-05-30 17:15:17.668500

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "013"
down_revision: Union[str, None] = "012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("card_amount", sa.Integer(), nullable=True))
    op.execute(
        "UPDATE transactions SET card_amount = COALESCE(card_balance_in, 0) - COALESCE(card_balance_out, 0)"
    )
    op.alter_column("transactions", "card_amount", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "card_amount")
    # ### end Alembic commands ###
