"""update customer

Revision ID: 014
Revises: 013
Create Date: 2025-06-11 19:09:09.545690

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "014"
down_revision: Union[str, None] = "013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customers", "phone_number", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_index("ix_customers_email", table_name="customers")
    op.drop_constraint("uix_customer_company_email", "customers", type_="unique")
    op.create_unique_constraint(
        "uix_customer_company_phone_number", "customers", ["company_id", "phone_number"]
    )
    op.drop_column("customers", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customers",
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("uix_customer_company_phone_number", "customers", type_="unique")
    op.create_unique_constraint(
        "uix_customer_company_email", "customers", ["company_id", "email"]
    )
    op.create_index("ix_customers_email", "customers", ["email"], unique=False)
    op.alter_column(
        "customers", "phone_number", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
