"""empty message

Revision ID: 069865168114
Revises: 001
Create Date: 2025-05-12 14:16:55.306252

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "069865168114"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uix_transaction_controller_transaction_id",
        "transactions",
        ["controller_transaction_id", "controller_id", "created_at_controller"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uix_transaction_controller_transaction_id", "transactions", type_="unique"
    )
    # ### end Alembic commands ###
