"""add fiscalizer type

Revision ID: 16
Revises: 015
Create Date: 2025-06-23 14:21:54.537272

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "16"
down_revision: Union[str, None] = "015"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fiscalizer_controllers",
        sa.Column("controller_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["controller_id"],
            ["controllers.id"],
        ),
        sa.PrimaryKeyConstraint("controller_id"),
    )
    op.create_table(
        "fiscalizer_transactions",
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.sync_enum_values(  # type: ignore
        enum_schema="public",
        enum_name="controllertype",
        new_values=["CARWASH", "WATER_VENDING", "VACUUM", "FISCALIZER"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="controllers", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(  # type: ignore
        enum_schema="public",
        enum_name="transactiontype",
        new_values=["CARWASH", "WATER_VENDING", "VACUUM", "FISCALIZER"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="transactions", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore
        enum_schema="public",
        enum_name="transactiontype",
        new_values=["CARWASH", "WATER_VENDING", "VACUUM"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="transactions", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(  # type: ignore
        enum_schema="public",
        enum_name="controllertype",
        new_values=["CARWASH", "WATER_VENDING", "VACUUM"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="controllers", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.drop_table("fiscalizer_transactions")
    op.drop_table("fiscalizer_controllers")
    # ### end Alembic commands ###
