"""add controllers.qr

Revision ID: 17
Revises: 16
Create Date: 2025-07-01 02:29:50.262080

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from dash.models.controllers.controller import ControllerType
from dash.services.controller.utils import generate_qr

# revision identifiers, used by Alembic.
revision: str = "17"
down_revision: Union[str, None] = "16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("controllers", sa.Column("qr", sa.String(), nullable=True))

    conn = op.get_bind()
    controllers = conn.execute(sa.text("SELECT id, type FROM controllers")).fetchall()
    existing_qrs = set()

    for controller in controllers:
        qr = generate_qr(ControllerType[controller.type])
        while qr in existing_qrs:
            qr = generate_qr(ControllerType[controller.type])
        existing_qrs.add(qr)
        conn.execute(
            sa.text("UPDATE controllers SET qr = :qr WHERE id = :id"),
            {"qr": qr, "id": controller.id},
        )

    op.alter_column("controllers", "qr", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("controllers", "qr")
    # ### end Alembic commands ###
