"""add controller.min_deposit_amount, add quick_deposit_buttons to fiscalizer controller

Revision ID: 20
Revises: 19
Create Date: 2025-07-06 00:13:25.400443

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20"
down_revision: Union[str, None] = "19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "controllers", sa.Column("min_deposit_amount", sa.Integer(), nullable=True)
    )
    op.execute("UPDATE controllers SET min_deposit_amount = 100")
    op.alter_column("controllers", "min_deposit_amount", nullable=False)

    op.add_column(
        "fiscalizer_controllers",
        sa.Column("quick_deposit_button_1", sa.Integer(), nullable=True),
    )
    op.add_column(
        "fiscalizer_controllers",
        sa.Column("quick_deposit_button_2", sa.Integer(), nullable=True),
    )
    op.add_column(
        "fiscalizer_controllers",
        sa.Column("quick_deposit_button_3", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fiscalizer_controllers", "quick_deposit_button_3")
    op.drop_column("fiscalizer_controllers", "quick_deposit_button_2")
    op.drop_column("fiscalizer_controllers", "quick_deposit_button_1")
    op.drop_column("controllers", "min_deposit_amount")
    # ### end Alembic commands ###
