"""add sim_number & sim_serial to fiscalizer

Revision ID: 21
Revises: 20
Create Date: 2025-07-11 17:15:30.985304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21"
down_revision: Union[str, None] = "20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fiscalizer_controllers", sa.Column("sim_number", sa.String(), nullable=True)
    )
    op.add_column(
        "fiscalizer_controllers", sa.Column("sim_serial", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fiscalizer_controllers", "sim_serial")
    op.drop_column("fiscalizer_controllers", "sim_number")
    # ### end Alembic commands ###
