"""add fiscalizer_controllers.description

Revision ID: 22
Revises: 21
Create Date: 2025-07-24 21:09:51.227351

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22"
down_revision: Union[str, None] = "21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fiscalizer_controllers", sa.Column("description", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fiscalizer_controllers", "description")
    # ### end Alembic commands ###
