"""add companies.phone_number, companies.email

Revision ID: 23
Revises: 22
Create Date: 2025-07-25 13:20:40.096289

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23"
down_revision: Union[str, None] = "22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("phone_number", sa.String(), nullable=True))
    op.add_column("companies", sa.Column("email", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "email")
    op.drop_column("companies", "phone_number")
    # ### end Alembic commands ###
