"""add controller.fiscalize_cash

Revision ID: 25
Revises: 24
Create Date: 2025-07-31 15:54:56.698063

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25"
down_revision: Union[str, None] = "24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "controllers", sa.Column("fiscalize_cash", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE controllers SET fiscalize_cash = true")
    op.alter_column("controllers", "fiscalize_cash", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("controllers", "fiscalize_cash")
    # ### end Alembic commands ###
