"""add vacuum_transactions

Revision ID: 27
Revises: 26
Create Date: 2025-08-12 14:41:55.278152

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "27"
down_revision: Union[str, None] = "26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vacuum_transactions",
        sa.Column(
            "services_sold_seconds",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
    )
    op.add_column(
        "vacuum_transactions",
        sa.Column("tariff", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column(
        "vacuum_transactions",
        sa.Column("replenishment_ratio", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacuum_transactions", "replenishment_ratio")
    op.drop_column("vacuum_transactions", "tariff")
    op.drop_column("vacuum_transactions", "services_sold_seconds")
    # ### end Alembic commands ###
