"""add customers.last_balance_update

Revision ID: 30
Revises: 29
Create Date: 2025-08-28 17:54:03.681565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30"
down_revision: Union[str, None] = "29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customers",
        sa.Column("last_balance_update", sa.DateTime(timezone=True), nullable=True),
    )
    op.execute("UPDATE customers SET last_balance_update = COALESCE(updated_at, created_at)")
    op.alter_column("customers", "last_balance_update", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "last_balance_update")
    # ### end Alembic commands ###
