"""add customers.readable_card_code

Revision ID: 31
Revises: 30
Create Date: 2025-09-04 15:14:08.342413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31"
down_revision: Union[str, None] = "30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customers", sa.Column("readable_card_code", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "readable_card_code")
    # ### end Alembic commands ###
