"""add controllers.last_reboot

Revision ID: 31
Revises: 30
Create Date: 2025-09-09 14:00:18.356363

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31"
down_revision: Union[str, None] = "30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "controllers",
        sa.Column("last_reboot", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("controllers", "last_reboot")
    # ### end Alembic commands ###
