"""add dummy_controllers/transactions

Revision ID: 32
Revises: 31
Create Date: 2025-09-09 15:23:45.611748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "32"
down_revision: Union[str, None] = "31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dummy_controllers",
        sa.Column("controller_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["controller_id"],
            ["controllers.id"],
        ),
        sa.PrimaryKeyConstraint("controller_id"),
    )
    op.create_table(
        "dummy_transactions",
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.sync_enum_values(  # type: ignore
        enum_schema="public",
        enum_name="controllertype",
        new_values=[
            "CARWASH",
            "WATER_VENDING",
            "VACUUM",
            "FISCALIZER",
            "LAUNDRY",
            "CAR_CLEANER",
            "DUMMY",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="controllers", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(  # type: ignore
        enum_schema="public",
        enum_name="transactiontype",
        new_values=[
            "CARWASH",
            "WATER_VENDING",
            "VACUUM",
            "FISCALIZER",
            "LAUNDRY",
            "CAR_CLEANER",
            "DUMMY",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="transactions", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dummy_transactions")
    op.drop_table("dummy_controllers")

    op.sync_enum_values(  # type: ignore
        enum_schema="public",
        enum_name="transactiontype",
        new_values=[
            "CARWASH",
            "WATER_VENDING",
            "VACUUM",
            "FISCALIZER",
            "LAUNDRY",
            "CAR_CLEANER",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="transactions", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(  # type: ignore
        enum_schema="public",
        enum_name="controllertype",
        new_values=[
            "CARWASH",
            "WATER_VENDING",
            "VACUUM",
            "FISCALIZER",
            "LAUNDRY",
            "CAR_CLEANER",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="controllers", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
