"""remove dummy transaction

Revision ID: 33
Revises: 32
Create Date: 2025-09-09 16:58:49.820708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "33"
down_revision: Union[str, None] = "32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dummy_transactions")
    op.sync_enum_values(  # type: ignore
        enum_schema="public",
        enum_name="transactiontype",
        new_values=[
            "CARWASH",
            "WATER_VENDING",
            "VACUUM",
            "FISCALIZER",
            "LAUNDRY",
            "CAR_CLEANER",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="transactions", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore
        enum_schema="public",
        enum_name="transactiontype",
        new_values=[
            "CARWASH",
            "WATER_VENDING",
            "VACUUM",
            "FISCALIZER",
            "LAUNDRY",
            "CAR_CLEANER",
            "DUMMY",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="transactions", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.create_table(
        "dummy_transactions",
        sa.Column("transaction_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name="dummy_transactions_transaction_id_fkey",
        ),
        sa.PrimaryKeyConstraint("transaction_id", name="dummy_transactions_pkey"),
    )
    # ### end Alembic commands ###
