"""add payment.extra

Revision ID: 35
Revises: 34
Create Date: 2025-09-15 14:48:53.343610

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "35"
down_revision: Union[str, None] = "34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.sync_enum_values(  # type: ignore
        enum_schema="public",
        enum_name="laundrysessionstatus",
        new_values=["WAITING_START", "IN_PROGRESS", "COMPLETED", "TIMEOUT", "ERROR"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="laundry_transactions",
                column_name="session_status",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore
        enum_schema="public",
        enum_name="laundrysessionstatus",
        new_values=[
            "PAYMENT_CONFIRMED",
            "WAITING_START",
            "IN_PROGRESS",
            "COMPLETED",
            "TIMEOUT",
            "ERROR",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="laundry_transactions",
                column_name="session_status",
            )
        ],
        enum_values_to_rename=[],
    )
    op.drop_column("payments", "extra")
    # ### end Alembic commands ###
