"""update laundry_controllers

Revision ID: 34
Revises: 33
Create Date: 2025-09-10 14:15:08.124675

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35"
down_revision: Union[str, None] = "34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "laundry_controllers",
        sa.Column("button_relay_id", sa.Integer(), nullable=True),
    )
    op.execute("UPDATE laundry_controllers SET button_relay_id = 1")
    op.alter_column("laundry_controllers", "button_relay_id", nullable=False)

    op.add_column(
        "laundry_controllers", sa.Column("led_output_id", sa.Integer(), nullable=True)
    )
    op.execute("UPDATE laundry_controllers SET led_output_id = 1")
    op.alter_column("laundry_controllers", "led_output_id", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("laundry_controllers", "led_output_id")
    op.drop_column("laundry_controllers", "button_relay_id")
    # ### end Alembic commands ###
