"""add user subscription fields

Revision ID: 38
Revises: 37
Create Date: 2025-09-16 19:01:48.487290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38"
down_revision: Union[str, None] = "37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin_users",
        sa.Column("subscription_paid_until", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "admin_users",
        sa.Column("subscription_payment_details", sa.String(), nullable=True),
    )
    op.add_column(
        "admin_users", sa.Column("subscription_amount", sa.Integer(), nullable=True)
    )
    op.add_column("admin_users", sa.Column("is_blocked", sa.Boolean(), nullable=True))
    op.execute("UPDATE admin_users SET is_blocked = false")
    op.alter_column("admin_users", "is_blocked", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admin_users", "is_blocked")
    op.drop_column("admin_users", "subscription_amount")
    op.drop_column("admin_users", "subscription_payment_details")
    op.drop_column("admin_users", "subscription_paid_until")
    # ### end Alembic commands ###
