"""change laundry_transactions.tariff_type str -> enum

Revision ID: 39
Revises: 38
Create Date: 2025-09-19 15:50:55.603788

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39"
down_revision: Union[str, None] = "38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "laundry_transactions",
        "tariff_type",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("FIXED", "PER_MINUTE", name="laundrytarifftype"),
        existing_nullable=False,
        postgresql_using="tariff_type::laundrytarifftype",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "laundry_transactions",
        "tariff_type",
        existing_type=sa.Enum("FIXED", "PER_MINUTE", name="laundrytarifftype"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
