"""add encashment unique contstraint

Revision ID: 42
Revises: 41
Create Date: 2025-09-24 18:30:34.991145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42"
down_revision: Union[str, None] = "41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "encashments",
        sa.Column("controller_encashment_id", sa.Integer(), nullable=True),
    )
    op.create_unique_constraint(
        "uix_encashment_controller_encashment_id",
        "encashments",
        ["controller_encashment_id", "controller_id", "created_at_controller"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uix_encashment_controller_encashment_id", "encashments", type_="unique"
    )
    op.drop_column("encashments", "controller_encashment_id")
    # ### end Alembic commands ###
